# -*- coding: utf-8 -*-
"""FASE5_MFMK_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NvDrQ0z7cHNVGI_pKTXmq4M-kERQYu5U
"""

#!pip install streamlit

#st.set_page_config(
#    page_title="PASSOS MÁGICOS",
#    layout="wide",
#)

#st.header("**PASSOS MÁGICOS**")

#st.write('Nossa História')

#st.write('A Associação Passos Mágicos tem uma trajetória de 33 anos de atuação, trabalhando na transformação da vida de crianças e jovens de baixa renda os levando a melhores oportunidades de vida.')

#st.write('O que fazemos?')

#st.write('Oferecemos um programa de educação de qualidade para crianças e jovens do município de Embu-Guaçu.')

#st.write('Clique no botão para acessar o site')

#st.write('Analise dos dados')

#st.write('Para acessar pelo notebook/desktop, clique no botão abaixo.')

#st.write('Para acessar pelo celular, clique no botão abaixo.')

import streamlit as st
import base64
from pathlib import Path


# ==========================================================
# CONFIGURAÇÃO DA PÁGINA
# ==========================================================

st.set_page_config(
    page_title="Passos Mágicos",
    page_icon="⭐",
    layout="wide"
)


# ==========================================================
# FUNDO + FORMATAÇÃO
# ==========================================================

def colocar_fundo(imagem):

    with open(imagem, "rb") as arquivo:
        imagem_base64 = base64.b64encode(
            arquivo.read()
        ).decode()

    st.markdown(
        f"""
        <style>

        /* Fundo da página */
        .stApp {{
            background-image:
                linear-gradient(
                    rgba(255,255,255,0.80),
                    rgba(255,255,255,0.80)
                ),
                url("data:image/png;base64,{imagem_base64}");

            background-size: cover;
            background-position: center;
            background-attachment: fixed;
        }}

        /* Limitar largura do conteúdo */
        .block-container {{
            padding-top: 2rem;
            padding-bottom: 3rem;
            max-width: 1200px;
        }}

        /* Título principal */
        .titulo-principal {{
            color: #1F5FAF;
            font-size: 48px;
            font-weight: 800;
            text-align: center;
            margin-bottom: 30px;
        }}

        /* Títulos das seções */
        .titulo-secao {{
            color: #D32F2F;
            font-size: 26px;
            font-weight: 800;
            margin-top: 25px;
            margin-bottom: 10px;
        }}

        /* Caixas dos textos */
        .caixa {{
            background-color: rgba(255,255,255,0.90);
            padding: 22px 25px;
            border-radius: 14px;
            box-shadow: 0px 3px 12px rgba(0,0,0,0.15);
            font-size: 18px;
            line-height: 1.6;
            margin-bottom: 15px;
        }}

        /* Botões */
        .stLinkButton a {{
            border-radius: 10px !important;
            font-weight: 700 !important;
        }}

        </style>
        """,
        unsafe_allow_html=True
    )


BASE_DIR = Path(__file__).parent

colocar_fundo(BASE_DIR / "fundo_passos_magicos.png")


# ==========================================================
# TÍTULO
# ==========================================================

st.markdown(
    '<div class="titulo-principal">⭐ PASSOS MÁGICOS ⭐</div>',
    unsafe_allow_html=True
)


# ==========================================================
# NOSSA HISTÓRIA
# ==========================================================

st.markdown(
    '<div class="titulo-secao">Nossa História</div>',
    unsafe_allow_html=True
)

st.markdown(
    """
    <div class="caixa">
    A Associação Passos Mágicos tem uma trajetória de 33 anos de atuação,
    trabalhando na transformação da vida de crianças e jovens de baixa renda,
    levando-os a melhores oportunidades de vida.
    </div>
    """,
    unsafe_allow_html=True
)


# ==========================================================
# O QUE FAZEMOS
# ==========================================================

st.markdown(
    '<div class="titulo-secao">O que fazemos?</div>',
    unsafe_allow_html=True
)

st.markdown(
    """
    <div class="caixa">
    Oferecemos um programa de educação de qualidade para crianças e jovens
    do município de Embu-Guaçu.
    </div>
    """,
    unsafe_allow_html=True
)


# ==========================================================
# SITE DA PASSOS MÁGICOS
# ==========================================================

st.markdown(
    '<div class="titulo-secao">Conheça a Passos Mágicos</div>',
    unsafe_allow_html=True
)

st.link_button(
    "🌐 Acessar site da Passos Mágicos",
    "https://passosmagicos.org.br/",
    use_container_width=True
)


# ==========================================================
# ANÁLISE DOS DADOS
# ==========================================================

st.markdown(
    '<div class="titulo-secao">Análise dos Dados</div>',
    unsafe_allow_html=True
)

st.markdown(
    """
    <div class="caixa">
    Explore os dashboards desenvolvidos para análise dos indicadores
    educacionais da Passos Mágicos.
    </div>
    """,
    unsafe_allow_html=True
)


col1, col2 = st.columns(2)

with col1:

    st.link_button(
        "💻 Acessar Dashboard - Notebook / Desktop",
        "https://app.powerbi.com/view?r=eyJrIjoiZDY0NjkyZmQtY2RjYS00Mzg4LTgyN2UtMTVhZDgzYmJkMTYxIiwidCI6IjIwNDRhZjJlLTQyOWItNDBhMi04MzI2LTUyNmU1NDVjNGJlOSJ9",
        use_container_width=True
    )


with col2:

    st.link_button(
        "📱 Acessar Dashboard - Celular",
        "COLOQUE_AQUI_O_LINK_POWER_BI_MOBILE",
        use_container_width=True
    )